### ISSUE TITLE
Your ocaml installation seems broken, please fix it

### ISSUE THREAD

**Issue by mictadlo** [MLstate/opalang#146]
Hi,
I tried to compile Opa web framework from source on Sabayon, because their main server has a hardware failure. However, when I tried to use configure I got "Your ocaml installation seems broken, please fix it" massage. I tried to reinstall ocaml, but it changed nothing.

    $ equo install nodejs openssl mongodb ocaml git ocaml-autoconf camlp ocamlgraph camlzip ulex
    $ git clone https://github.com/MLstate/opalang

    $ ./configure -ocamlfind `which ocamlfind` --prefix=/home/mictadlo/apps/
    which: no ocamlfind in (/home/mictadlo/apps/Sublime Text 2:/home/mictadlo/apps/WebStorm/bin:/home/mictadlo/apps/netbeans/bin:/home/mictadlo/apps/pymodules/bin:/home/mictadlo/apps/bin:/bin:/home/mictadlo/apps/go_packages/bin:/home/mictadlo/apps/liteide/bin/:/home/mictadlo/apps/snap:/home/mictadlo/apps/node_modules/bin:/usr/local/bin:/usr/bin:/bin:/opt/bin:/usr/x86_64-pc-linux-gnu/gcc-bin/4.7.3:/usr/games/bin)
    Checking your OS... Linux
    Checking your architecture... x86_64
    Checking ocamlopt... /usr/bin/ocamlopt.opt
    Checking ocamlbuild... /usr/bin/ocamlbuild
    Checking ocamldir... /usr/lib64/ocaml
    Checking ocaml version... 4.01.0
    Checking your ocaml setup... could not compile
    ----------
            /usr/lib64/ocaml/libasmrun.a: could not read symbols: Bad value
            collect2: error: ld returned 1 exit status
            File "caml_startup", line 1:
            Error: Error during linking
            Command exited with code 2.
    ----------
    Your ocaml installation seems broken, please fix it

I also posted the question here http://unix.stackexchange.com/questions/117597/ocaml-seems-to-be-broken .

How is it possible to fix the problem?

Thank you in advance.

**Comment by hbbio** [comment]
This seems a custom problem with your OCaml installation unrelated to Opa.
