### ISSUE TITLE
vagrant up - doesn't work!  >>  test01.mlstate.com/opa.box - 403 Forbidden

### ISSUE THREAD

**Issue by nsuhach** [MLstate/opalang#152]
$ vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Box 'mlstate/opa' could not be found. Attempting to find and install...
default: Box Provider: virtualbox
default: Box Version: >= 0
==> default: Loading metadata for box 'mlstate/opa'
default: URL: https://vagrantcloud.com/mlstate/opa
==> default: Adding box 'mlstate/opa' (v1.1.1) for provider: virtualbox
default: Downloading: https://vagrantcloud.com/mlstate/opa/version/1/provider/virtualbox.box
An error occurred while downloading the remote file. The error
message, if any, is reproduced below. Please fix this error and try
again.

The requested URL returned error: 403 Forbidden

**Comment by izderadicka** [comment]
Same here - I think problem is that actual link is to  Google drive -   and  rather then providing files it open page asking for confirmation.

**Comment by hbbio** [comment]
Closing, as we either recommend to build from source or switch to forthcoming Docker containers ready for Opa development.

**Comment by minimallinux** [comment]
I had a similar error (on Centos 7), saying  -  default: Adding box 'mlstate/opa' (v1.2.0) for provider: virtualbox
    default: Downloading: https://vagrantcloud.com/mlstate/boxes/opa/versions/1.2.0/providers/virtualbox.box
unrecognised archive format.

**Comment by minimallinux** [comment]
Sorry just noticed its closed !
