### ISSUE TITLE
I would like to get a complete formal grammar of Opa

### ISSUE THREAD

**Issue by Shiroy** [MLstate/opalang#171]
I have the project to write a tool similar to Doxygen for Opa. I've seen that a tool called opadoc already exist but I cannot find it.

My project is to create a tool which analyse the source code and read comments annotations to generate html pages, in a first time.
 
For that I need a complete formal grammar of Opa. I don't know if such a document exists. I've seen a partial formal grammar in the wiki but is not enough to parse common Opa project.

If you have it, could you send me this document ?

Regards

**Comment by HenriChataing** [comment]
Hi, I am not sure whether we have a formal description of the syntax or not (I am not part of the original Opa developer team), but you can try using the compiler's syntax file: [opa_parser.trx](https://github.com/MLstate/opalang/blob/master/compiler/opalang/js_syntax/opa_parser.trx).

**Comment by hbbio** [comment]
Also, the following work might be of interest for you:

https://github.com/facebook/pfff/tree/master/lang_opa

**Comment by Shiroy** [comment]
Oh yes ! It's exactly what I need :)

**Comment by leftys** [comment]
Hello @Shiroy! I was thinking about generating doc for opa too. Did you have any results with your effort?

**Comment by Shiroy** [comment]
Hello @leftys . No, I didn't persist in this way because of a lack of time due to my study and my internship.
