### ISSUE TITLE
Can't build from sources on Ubuntu 14.10 : Unbound module Bytes

### ISSUE THREAD

**Issue by Xosted** [MLstate/opalang#172]
Hi,

I followed the instruction to build Opa on a Linux machine from sources. It goes as far as `./configure` without error but `make` returns:
```
opalang$ make
Ocamlbuild generation
File "./tools/build/myocamlbuild_prefix.ml", line 26, characters 10-20:
Error: Unbound module Bytes
tools/build/Makefile.bld:80: recipe for target '_build/myocamlbuild.exe' failed
make: *** [_build/myocamlbuild.exe] Error 2
```
Regards

**Comment by HenriChataing** [comment]
Your version of ocaml is not up to date. The latest build introduces the module `Bytes` for the manipulation of *mutable* strings.

**Comment by Xosted** [comment]
Ok, thank you for the fast reply.
I'm trying to get a new version of ocaml from their website, apparently, it isn't simple.

But shouldn't the guides be updated to enforce the necessary version?
For beginners like me, it is not so obvious.
Actually, it is a bit discouraging for the ones who want to try like me. The command line install guide through package didn't work (I went around finding THE link which works, but packages are from 2013), the guide to build from source didn't work and the vagrant option didn't work either (some unrecognized archive format).

Regards

**Comment by hbbio** [comment]
It's added in the [building page](https://github.com/MLstate/opalang/wiki/Building-Opa).
