### ISSUE TITLE
Can't build from sources on Ubuntu 14.04 : Command exited with code 137

### ISSUE THREAD

**Issue by Xosted** [MLstate/opalang#174]
Hi,

I'm still trying to build Opa from sources. Even with the updated guide and new version of ocaml, I couldn't get there. To avoid running into errors before I get to launch `make` I applied the old process, pretty much, without ocaml-findlib which couldn't be installed because of broken dependencies (it seems to be stuck requesting another package at 4.01 version, even if the 4.02 is installed).
This runs fine and returns that I'm ready to go. `make` runs for a while then stays stuck at `1089 (1087) compiler/opalang/js_syntax/opa_js_parser.cmx` then ends with:
```
+ /usr/bin/ocamlopt -c -g -warn-error A -w L -w Z -I ocamllib/libbase -I compiler/buildinfos -I compiler/compilerlib -I compiler/libqmlcompil -I compiler/libtrx -I compiler/opacapi -I compiler/passlib -I compiler/opalang -I compiler/opalang/classic_syntax -I compiler/opalang/js_syntax -I tools -I compiler -I lib -I ocamllib -I tools/build -o compiler/opalang/classic_syntax/opa_classic_parser.cmx compiler/opalang/classic_syntax/opa_classic_parser.ml
Killed
Command exited with code 137.
Compilation unsuccessful after building 1089 targets (1087 cached) in 00:02:41.
make: *** [node] Error 10
```

Regards

**Comment by hbbio** [comment]
It says: Killed.

Add more RAM.

**Comment by Xosted** [comment]
You were right, my bad. I had to allocate 2GB to the virtual machine for the compilation to succeed. It seems that now I have managed to get it up and running. I'll go on and test it now.

This is probably a stupid question but.. where is the community communication happening? Is there a forum where I can find assistance instead of bothering you guys all the time with error reports?

Regards
