### ISSUE TITLE
Forum is dead

### ISSUE THREAD

**Issue by mindplay-dk** [MLstate/opalang#176]
The [Opa forum](http://forum.opalang.org/) is dead?

**Comment by ArtemGr** [comment]
BTW. So I heard there's no time (=funding) to maintain the forum (http://lists.owasp.org/pipermail/opa/2014-February/001229.html). How about Reddit then? For example the Rust language mentions Reddit on their page (http://prntscr.com/6ge1h1) and they've got a huge community there, probably the most of the users (me included) communicate via Reddit. Why not go that rote while the forum is waiting for some love?

**Comment by hbbio** [comment]
I recommend to use [StackOverflow](http://stackoverflow.com/questions/tagged/opa) instead.
