### ISSUE TITLE
Compilation error , static resources 

### ISSUE THREAD

**Issue by nitrox62** [MLstate/opalang#180]
![Uploading Capture d’écran 2015-03-19 à 19.19.16.png . . .]()

Error: File "salut.opa", line 37, characters 0-0, (37:0-37:0 | 704-704)
Syntax error
  The error may be in the following citation, usually in the red part
  (starting at ⚐) or just before:

 
}

Server.start(Server.http, 
{title: "Jeu du plus et du moins", page: page}
⚐[ {resources: @static_include_directory("resources")},
{register: {css:["/resources/style-1.css"]}},

 ]

)
Hint:
  expected "" or "&" or ")" or "," or "<" or "=" or "?" or "@" or "as" or "|" or "||" or <spacing> or <xhtml> 
(while parsing <expression unary '-'> starting at line 36, column 41)
Hint:
  The body, found at (26:2-26:5), might be open

Anyone has an idea?  When I delete the resources at the end , all is ok .

**Comment by HenriChataing** [comment]
You are missing a comma after the {title: ..} record.

2015-03-19 19:16 GMT+01:00 nitrox62 <notifications@github.com>:

**Comment by nitrox62** [comment]
Ok I am at a conférence I will look mater.thank you

**Comment by hbbio** [comment]
This is not an issue.
