### ISSUE TITLE
Can't build from sources on Ubuntu 14.10 : Unbound module Bytes

### ISSUE THREAD

**Issue by monkeymarco80** [MLstate/opalang#182]
i saw last question and answer
https://github.com/MLstate/opalang/wiki/Building-Opa
i follow this Older Ubuntu/Debian systems
but  i can't build

ERROR MESSAGE

Ocamlbuild generation
File "./tools/build/myocamlbuild_prefix.ml", line 26, characters 10-20:
Error: Unbound module Bytes
tools/build/Makefile.bld:80: recipe for target '_build/myocamlbuild.exe' failed
make: *** [_build/myocamlbuild.exe] Error 2

**Comment by HenriChataing** [comment]
Hi, your version of OCaml is not up to date.

**Comment by Check-mate** [comment]
Hi,
I had the same error.
Add this environment value
**source ~/ocamlbrew/ocaml-**_4.02.1_**/etc/ocamlbrew.bashrc**
The installed version of OCaml can vary.
Go to your *ocamlbrew* folder in your home and check the name of the ocaml folder
**cd ~/ocamlbrew**
You can rebuild Opa. It should work now.
