### ISSUE TITLE
Can’t install Opa on Trisquel 7

### ISSUE THREAD

**Issue by VeryTastyTomato** [MLstate/opalang#183]
Hello,

I tried to install Opa by following [this page] (https://github.com/MLstate/opalang/wiki/Building-Opa) instructions, under the section “Modern Linux system”, except that I didn't install ocamlbrew. I used the command *./configure* and installed the missing package, and then I used the commande *make*. But here it failed.

First it displays a lot of warnings about unused flag declaration, then it display errors and stop. You’ll find below the messages that are relevant in my opinion:

```
[!] Git repo info for opalang not found
…
File "compiler/buildinfos/buildInfos.ml", line 20, characters 2-17:
Error: Unbound value opa_git_version
Command exited with code 2.
Compilation unsuccessful after building 500 targets (0 cached) in 00:00:19.
make: *** [node] Erreur 10
```

Oh, just to be sure, Trisquel is derived from Ubuntu.

**Comment by HenriChataing** [comment]
This error occured when installing opa on a non-english OS. I fixed it in the last commit.
