### ISSUE TITLE
make: *** No rule to make target 'tools/build/config.make'. Stop.

### ISSUE THREAD

**Issue by dicksoncreative** [MLstate/opalang#189]
I followed the instructions for OS X at https://github.com/MLstate/opalang/wiki/Building-Opa to the letter and the error “make: *** No rule to make target 'tools/build/config.make'. Stop.” was thrown when I attempt to “make.” When I check the tools/build directory, there is no config.make file.

**Comment by hbbio** [comment]
Did you run configure?

**Comment by nathan43082** [comment]
If you mean the line before make, yes.

**Comment by nathan43082** [comment]
I just tried it again, beginning with the configure line right before it, and this is what happened.

    Nathans-Mac-Pro:opalang ndickson$ ./configure -ocamlfind 'which ocamlfind'
    Checking your OS... MacOS
    Checking your architecture... x86_64
    Checking for gsed... ok
    Checking for GNU coreutils... ok
    Checking ocamlopt... /usr/local/bin/ocamlopt.opt
    Checking ocamlbuild... /usr/local/bin/ocamlbuild
    Checking ocamldir... /usr/local/lib/ocaml
    Checking ocaml version... 4.02.3
    Checking your ocaml setup... 4.02.3, Unix 64bit
    Checking for camlp4... /usr/local/bin/camlp4o
    Checking for perl 5... found
    Checking for java... found
    Checking for nodejs... found: node
    Checking for nodejs version... v4.2.3
    Node v0.10.0 or newer is required
    Nathans-Mac-Pro:opalang ndickson$ make
    Makefile:32: tools/build/config.make: No such file or directory
    make: *** No rule to make target `tools/build/config.make'.  Stop.
    Nathans-Mac-Pro:opalang ndickson$

**Comment by NickMcG** [comment]
I just got the same thing. In your configure, you'll notice it is complaining about Node, saying that v4.2.3 is older than v0.10.0. This is because it is only comparing the middle number in the version and failing because 2 < 10.

The right fix for this is to do a full version comparison, but I got around it for now by changing line 334 of configure to go from:
     NODE_MIN_VERSION=10
to:
     NODE_MIN_VERSION=0

**Comment by hbbio** [comment]
Thanks. I confirm this is a valid patch and we'll change it soon on master. Opa is now compatible with most versions of Node.

**Comment by dicksoncreative** [comment]
Nick, that did fix the problem for now. Good sleuthing.

**Comment by dspring0021** [comment]
Is master not updated with the fix?  I just cloned, configured, and tried to make and got the exact same issue.  Happy to do the hack...just curious when the fix would be in place?

**Comment by hbbio** [comment]
Sorry, this should be pushed now!
