### ISSUE TITLE
Can't download and compile Opa in Ubuntu 14.04 LTS

### ISSUE THREAD

**Issue by riz007** [MLstate/opalang#192]
I followed the instructions to install Opa in my Ubuntu virtual machine, running on my Windows 64 bit platform, from https://github.com/MLstate/opalang/wiki/Building-Opa. I installed the files inside /bin directory but got the following error messages: 

riz@ubuntu:/bin$ cd opalang
riz@ubuntu:/bin/opalang$ sudo ./configure
[sudo] password for riz: 
Checking your OS... Linux
Checking your architecture... x86_64
Checking ocamlopt... /usr/bin/ocamlopt.opt
Checking ocamlbuild... /usr/bin/ocamlbuild
Checking ocamldir... /usr/lib/ocaml
Checking ocaml version... 4.02.3
Checking your ocaml setup... 4.02.3, Unix 64bit
Checking for camlp4... /usr/bin/camlp4o
Checking for perl 5... found
Checking for java... Not found
riz@ubuntu:/bin/opalang$ sudo make
Makefile:32: tools/build/config.make: No such file or directory
make: *** No rule to make target `tools/build/config.make'.  Stop.
riz@ubuntu:/bin/opalang$ sudo make install
Makefile:32: tools/build/config.make: No such file or directory
make: *** No rule to make target `tools/build/config.make'.  Stop.

How can I get rid of this issue? Any help would be appreciated. Thanks.

**Comment by hbbio** [comment]
You should not use sudo for configure.

Also, for the next step you're missing dependencies (java is needed for closure which we use to minimize generated JS).
