### ISSUE TITLE
ReferenceError: check_opa_deps is not defined

### ISSUE THREAD

**Issue by fuzzthink** [MLstate/opalang#193]
I'm trying to use opa as a compile to javascript language. I have a try.opa file of:

`print("s")`

and compile it with `opa try.opa`. It created a try.js file. Running it gives me

`ReferenceError: check_opa_deps is not defined` error.

I did installed the dependencies in package.json (edited the versions to be 1.0.6 since the produced versions of 1.2.0 did not exists).

```
{
  "name":"link",
  "version":"1.2.0",
  "main":"try.js",
  "dependencies":{
    "opabsl.opp":"1.0.6",
    "opa-js-runtime-cps":"1.0.6"
  }
}
```

Note that I did remove "stdlib.core.web.server.opx" from dependencies since it npm install errors as it doesn't seem to be found and I'm not using the web server.

Please let me know how I can proceed.

**Comment by hbbio** [comment]
As of now, you can not remove web.server from the dependencies. Otherwise, you may want to patch Opa to remove the dependency check.
