### ISSUE TITLE
Max OSX installation issue

### ISSUE THREAD

**Issue by igneel64** [MLstate/opalang#194]
Hello all! I seem to be having a problem installing OPA using the steps provided in the official files. All the steps have been made and the current state after running: 
` ./configure -ocamlfind 'which ocamlfind' ` <--backticks
is

> Checking your OS... MacOS
> Checking your architecture... x86_64
> Checking for gsed... ok
> Checking for GNU coreutils... ok
> Checking ocamlopt... /Users/petros/.opam/4.06.0/bin/ocamlopt.opt
> Checking ocamlbuild... /Users/petros/.opam/4.06.0/bin/ocamlbuild
> Checking ocamldir... /Users/petros/.opam/4.06.0/lib/ocaml
> Checking ocaml version... 4.06.0
> Checking your ocaml setup... 4.06.0, Unix 64bit
> Checking for camlp4... /Users/petros/.opam/4.06.0/bin/camlp4o
> Checking for perl 5... found
> Checking for java... found
> Checking for nodejs... found: node
> Checking for nodejs version... 8.4.0
> Checking for ocamlfind... /Users/petros/.opam/4.06.0/bin/ocamlfind
> Checking for ulex... ocamlfind:/Users/petros/.opam/4.06.0/lib/ulex, OK
> Checking for camlzip... ocamlfind:/Users/petros/.opam/4.06.0/lib/camlzip/../zip, OK
> Checking for ocamlgraph... ocamlfind:/Users/petros/.opam/4.06.0/lib/ocamlgraph, OK
> 
> Congrats, you're all set. Installation will be done in:
> 	/usr/local
> 

The problem is when I run `make` I get the following errors

> Ocamlbuild generation
> File "./tools/build/myocamlbuild_prefix.ml", line 502, characters 37-53:
> Warning 3: deprecated: Ocamlbuild_plugin.String.uppercase
> Use String.uppercase_ascii instead.
> File "./tools/build/build_rules.ml", line 490, characters 20-39:
> Warning 3: deprecated: Ocamlbuild_plugin.String.uncapitalize
> Use String.uncapitalize_ascii instead.
> File "./tools/build/build_rules.ml", line 490, characters 52-69:
> Warning 3: deprecated: Ocamlbuild_plugin.String.capitalize
> Use String.capitalize_ascii instead.
> File "./tools/build/build_rules.ml", line 495, characters 20-39:
> Warning 3: deprecated: Ocamlbuild_plugin.String.uncapitalize
> Use String.uncapitalize_ascii instead.
> File "./tools/build/build_rules.ml", line 495, characters 52-69:
> Warning 3: deprecated: Ocamlbuild_plugin.String.capitalize
> Use String.capitalize_ascii instead.
> _build/myocamlbuild.exe -no-plugin -j 6 -tag debug opabsl.qmljs.stamp plugins.qmljs.stamp compiler/main.native compiler/pplib/ppjs.native compiler/pplib/ppml.native compiler/opx2js/opx2js.native ocamllib/libbase/gen_platform tools/bash/bash_completion tools/teerex/trx_ocaml.native lib/plugins/opabsl/serverLib.cmi tools/teerex/trx_interpreter.native ocamllib/libbase/bslServerLib.ml compiler/libbsl/bslregister.native tools/jschecker/compiler.jar compiler/libbsl/bslbrowser.native tools/dissemination/spawn.sh compiler/libbsl/bslbrowser compiler/opa/gen_opa_manpage.native compiler/passlib/passdesign.native compiler/passlib/opatrack.sh compiler/compilerlib/opadep.sh ocamllib/libbase/testfilepos.native compiler/jslang/jsstat.native compiler/jslang/globalizer.native compiler/qmlcompilers/qmljs_exe.native tools/odep.native tools/odeplink.native compiler/opalang/opa2opa.native tools/ofile.native tools/manpages/genman.native compiler/opa/syntaxHelper.native compiler/opa/checkopacapi.native compiler/pplib/ppopa.native opa-node-packages.stamp qmljs.opa.create
> File "compiler/js_passes/_tags", line 7, characters 151-170:
> Warning: the tag "use_qmlfakecompiler" is not used in any flag or dependency declaration, so it will have no effect; it may be a typo. Otherwise you can use `mark_tag_used` in your myocamlbuild.ml to disable this warning.
> File "compiler/libbsl/_tags", line 6, characters 9-18:
> Warning: the tag "trx_cache" is not used in any flag or dependency declaration, so it will have no effect; it may be a typo. Otherwise you can use `mark_tag_used` in your myocamlbuild.ml to disable this warning.
> File "compiler/libbsl/_tags", line 10, characters 15-27:
> Warning: the tag "use_langlang" is not used in any flag or dependency declaration, so it will have no effect; it may be a typo. Otherwise you can use `mark_tag_used` in your myocamlbuild.ml to disable this warning.
> File "compiler/libbsl/_tags", line 30, characters 9-15:
> Warning: the tag "ignore" is not used in any flag or dependency declaration, so it will have no effect; it may be a typo. Otherwise you can use `mark_tag_used` in your myocamlbuild.ml to disable this warning.
> File "compiler/libbsl/_tags", line 33, characters 170-182:
> Warning: the tag "use_langlang" is not used in any flag or dependency declaration, so it will have no effect; it may be a typo. Otherwise you can use `mark_tag_used` in your myocamlbuild.ml to disable this warning.
> File "compiler/libtrx/_tags", line 1, characters 9-18:
> Warning: the tag "trx_cache" is not used in any flag or dependency declaration, so it will have no effect; it may be a typo. Otherwise you can use `mark_tag_used` in your myocamlbuild.ml to disable this warning.
> File "compiler/ocamllang/_tags", line 1, characters 20-29:
> Warning: the tag "trx_cache" is not used in any flag or dependency declaration, so it will have no effect; it may be a typo. Otherwise you can use `mark_tag_used` in your myocamlbuild.ml to disable this warning.
> File "compiler/opa/_tags", line 53, characters 60-79:
> Warning: the tag "use_qmlfakecompiler" is not used in any flag or dependency declaration, so it will have no effect; it may be a typo. Otherwise you can use `mark_tag_used` in your myocamlbuild.ml to disable this warning.
> File "compiler/opa/_tags", line 60, characters 130-149:
> Warning: the tag "use_qmlfakecompiler" is not used in any flag or dependency declaration, so it will have no effect; it may be a typo. Otherwise you can use `mark_tag_used` in your myocamlbuild.ml to disable this warning.
> File "compiler/opa/_tags", line 65, characters 262-281:
> Warning: the tag "use_qmlfakecompiler" is not used in any flag or dependency declaration, so it will have no effect; it may be a typo. Otherwise you can use `mark_tag_used` in your myocamlbuild.ml to disable this warning.
> File "compiler/opalang/_tags", line 17, characters 98-106:
> Warning: the tag "use_zlib" is not used in any flag or dependency declaration, so it will have no effect; it may be a typo. Otherwise you can use `mark_tag_used` in your myocamlbuild.ml to disable this warning.
> File "compiler/opalang/_tags", line 17, characters 67-76:
> Warning: the tag "use_mutex" is not used in any flag or dependency declaration, so it will have no effect; it may be a typo. Otherwise you can use `mark_tag_used` in your myocamlbuild.ml to disable this warning.
> File "compiler/opx2js/_tags", line 5, characters 227-246:
> Warning: the tag "use_qmlflatcompiler" is not used in any flag or dependency declaration, so it will have no effect; it may be a typo. Otherwise you can use `mark_tag_used` in your myocamlbuild.ml to disable this warning.
> File "compiler/opx2js/_tags", line 5, characters 206-225:
> Warning: the tag "use_qmlfakecompiler" is not used in any flag or dependency declaration, so it will have no effect; it may be a typo. Otherwise you can use `mark_tag_used` in your myocamlbuild.ml to disable this warning.
> File "compiler/qmlcps/_tags", line 4, characters 69-83:
> Warning: the tag "use_oparuntime" is not used in any flag or dependency declaration, so it will have no effect; it may be a typo. Otherwise you can use `mark_tag_used` in your myocamlbuild.ml to disable this warning.
> File "compiler/qmlcps/_tags", line 4, characters 53-67:
> Warning: the tag "use_appruntime" is not used in any flag or dependency declaration, so it will have no effect; it may be a typo. Otherwise you can use `mark_tag_used` in your myocamlbuild.ml to disable this warning.
> File "compiler/_tags", line 10, characters 213-232:
> Warning: the tag "use_qmlfakecompiler" is not used in any flag or dependency declaration, so it will have no effect; it may be a typo. Otherwise you can use `mark_tag_used` in your myocamlbuild.ml to disable this warning.
> File "lib/plugins/opabsl/_tags", line 20, characters 184-198:
> Warning: the tag "use_libsession" is not used in any flag or dependency declaration, so it will have no effect; it may be a typo. Otherwise you can use `mark_tag_used` in your myocamlbuild.ml to disable this warning.
> File "lib/plugins/opabsl/_tags", line 20, characters 166-182:
> Warning: the tag "use_qmlcpsserver" is not used in any flag or dependency declaration, so it will have no effect; it may be a typo. Otherwise you can use `mark_tag_used` in your myocamlbuild.ml to disable this warning.
> File "lib/plugins/opabsl/_tags", line 20, characters 152-164:
> Warning: the tag "use_database" is not used in any flag or dependency declaration, so it will have no effect; it may be a typo. Otherwise you can use `mark_tag_used` in your myocamlbuild.ml to disable this warning.
> File "lib/plugins/opabsl/_tags", line 20, characters 135-150:
> Warning: the tag "use_libsecurity" is not used in any flag or dependency declaration, so it will have no effect; it may be a typo. Otherwise you can use `mark_tag_used` in your myocamlbuild.ml to disable this warning.
> File "lib/plugins/opabsl/_tags", line 20, characters 123-133:
> Warning: the tag "use_libnet" is not used in any flag or dependency declaration, so it will have no effect; it may be a typo. Otherwise you can use `mark_tag_used` in your myocamlbuild.ml to disable this warning.
> File "lib/plugins/opabsl/_tags", line 20, characters 107-121:
> Warning: the tag "use_oparuntime" is not used in any flag or dependency declaration, so it will have no effect; it may be a typo. Otherwise you can use `mark_tag_used` in your myocamlbuild.ml to disable this warning.
> File "lib/plugins/opabsl/_tags", line 20, characters 91-105:
> Warning: the tag "use_appruntime" is not used in any flag or dependency declaration, so it will have no effect; it may be a typo. Otherwise you can use `mark_tag_used` in your myocamlbuild.ml to disable this warning.
> File "lib/plugins/opabsl/_tags", line 20, characters 75-89:
> Warning: the tag "use_libruntime" is not used in any flag or dependency declaration, so it will have no effect; it may be a typo. Otherwise you can use `mark_tag_used` in your myocamlbuild.ml to disable this warning.
> File "lib/plugins/opabsl/_tags", line 32, characters 181-195:
> Warning: the tag "use_oparuntime" is not used in any flag or dependency declaration, so it will have no effect; it may be a typo. Otherwise you can use `mark_tag_used` in your myocamlbuild.ml to disable this warning.
> File "lib/plugins/opabsl/_tags", line 32, characters 165-179:
> Warning: the tag "use_libsession" is not used in any flag or dependency declaration, so it will have no effect; it may be a typo. Otherwise you can use `mark_tag_used` in your myocamlbuild.ml to disable this warning.
> File "lib/plugins/opabsl/_tags", line 32, characters 149-163:
> Warning: the tag "use_libruntime" is not used in any flag or dependency declaration, so it will have no effect; it may be a typo. Otherwise you can use `mark_tag_used` in your myocamlbuild.ml to disable this warning.
> File "lib/plugins/opabsl/_tags", line 32, characters 131-147:
> Warning: the tag "use_qmlcpsserver" is not used in any flag or dependency declaration, so it will have no effect; it may be a typo. Otherwise you can use `mark_tag_used` in your myocamlbuild.ml to disable this warning.
> File "lib/plugins/opabsl/_tags", line 32, characters 117-129:
> Warning: the tag "use_database" is not used in any flag or dependency declaration, so it will have no effect; it may be a typo. Otherwise you can use `mark_tag_used` in your myocamlbuild.ml to disable this warning.
> File "lib/plugins/opabsl/_tags", line 32, characters 100-115:
> Warning: the tag "use_libsecurity" is not used in any flag or dependency declaration, so it will have no effect; it may be a typo. Otherwise you can use `mark_tag_used` in your myocamlbuild.ml to disable this warning.
> File "lib/plugins/opabsl/_tags", line 32, characters 84-98:
> Warning: the tag "use_appruntime" is not used in any flag or dependency declaration, so it will have no effect; it may be a typo. Otherwise you can use `mark_tag_used` in your myocamlbuild.ml to disable this warning.
> File "lib/plugins/opabsl/_tags", line 32, characters 72-82:
> Warning: the tag "use_libnet" is not used in any flag or dependency declaration, so it will have no effect; it may be a typo. Otherwise you can use `mark_tag_used` in your myocamlbuild.ml to disable this warning.
> File "lib/plugins/_tags", line 10, characters 20-26:
> Warning: the tag "static" is not used in any flag or dependency declaration, so it will have no effect; it may be a typo. Otherwise you can use `mark_tag_used` in your myocamlbuild.ml to disable this warning.
> File "tools/teerex/_tags", line 5, characters 9-18:
> Warning: the tag "trx_cache" is not used in any flag or dependency declaration, so it will have no effect; it may be a typo. Otherwise you can use `mark_tag_used` in your myocamlbuild.ml to disable this warning.

Error appearing
> /Users/petros/.opam/4.06.0/bin/ocamlc.opt -c -g -warn-error A -w L -w Z -I compiler/buildinfos -I tools -I ocamllib -I lib -I compiler -I tools/build -o compiler/buildinfos/buildInfos.cmo compiler/buildinfos/buildInfos.ml
> File "compiler/buildinfos/buildInfos.ml", line 42, characters 12-27:
> Error (warning 52): Code should not depend on the actual values of
> this constructor's arguments. They are only for information
> and may change in future versions. (See manual section 8.5)
> File "compiler/buildinfos/buildInfos.ml", line 76, characters 12-27:
> Error (warning 52): Code should not depend on the actual values of
> this constructor's arguments. They are only for information
> and may change in future versions. (See manual section 8.5)
> Command exited with code 2.
> Compilation unsuccessful after building 10 targets (9 cached) in 00:00:03.
> make: *** [node] Error 10

May you please help me with this or give me some guidelines?

Thanks!

**Comment by hbbio** [comment]
Opa is not compatible with OCaml 4.06. You need to downgrade OCaml, which is easy to do with `opam`.

**Comment by igneel64** [comment]
@hbbio Thanks for the reply, is there any maximum supported version? If it is not mentioned already (couldn't found it) we should add that to the docs.

**Comment by hbbio** [comment]
Can you try with 4.04.1 (maybe .2)?

**Comment by igneel64** [comment]
Have tried it with:
`opam switch 4.04.2`

After installing some of the packages required using opam

I got the result of ocamlfind:

```
Checking your OS... MacOS
Checking your architecture... x86_64
Checking for gsed... ok
Checking for GNU coreutils... ok
Checking ocamlopt... /Users/petros/.opam/4.04.2/bin/ocamlopt.opt
Checking ocamlbuild... /Users/petros/.opam/4.04.2/bin/ocamlbuild
Checking ocamldir... /Users/petros/.opam/4.04.2/lib/ocaml
Checking ocaml version... 4.04.2
Checking your ocaml setup... 4.04.2, Unix 64bit
Checking for camlp4... /Users/petros/.opam/4.04.2/bin/camlp4o
Checking for perl 5... found
Checking for java... found
Checking for nodejs... found: node
Checking for nodejs version... 8.4.0
Checking for ocamlfind... /Users/petros/.opam/4.04.2/bin/ocamlfind
Checking for ulex... ocamlfind:/Users/petros/.opam/4.04.2/lib/ulex, OK
Checking for camlzip... ocamlfind:/Users/petros/.opam/4.04.2/lib/camlzip/../zip, OK
Checking for ocamlgraph... ocamlfind:/Users/petros/.opam/4.04.2/lib/ocamlgraph, OK

Congrats, you're all set. Installation will be done in:
	/usr/local
```
After that 'make' produced another error:

> Ocamlbuild generation
> File "./tools/build/myocamlbuild_prefix.ml", line 502, characters 37-53:
> Warning 3: deprecated: Ocamlbuild_plugin.String.uppercase
> Use String.uppercase_ascii instead.
> File "./tools/build/build_rules.ml", line 490, characters 20-39:
> Warning 3: deprecated: Ocamlbuild_plugin.String.uncapitalize
> Use String.uncapitalize_ascii instead.
> File "./tools/build/build_rules.ml", line 490, characters 52-69:
> Warning 3: deprecated: Ocamlbuild_plugin.String.capitalize
> Use String.capitalize_ascii instead.
> File "./tools/build/build_rules.ml", line 495, characters 20-39:
> Warning 3: deprecated: Ocamlbuild_plugin.String.uncapitalize
> Use String.uncapitalize_ascii instead.
> File "./tools/build/build_rules.ml", line 495, characters 52-69:
> Warning 3: deprecated: Ocamlbuild_plugin.String.capitalize
> Use String.capitalize_ascii instead.
> _build/myocamlbuild.exe -no-plugin -j 6 -tag debug opabsl.qmljs.stamp plugins.qmljs.stamp compiler/main.native compiler/pplib/ppjs.native compiler/pplib/ppml.native compiler/opx2js/opx2js.native ocamllib/libbase/gen_platform tools/bash/bash_completion tools/teerex/trx_ocaml.native lib/plugins/opabsl/serverLib.cmi tools/teerex/trx_interpreter.native ocamllib/libbase/bslServerLib.ml compiler/libbsl/bslregister.native tools/jschecker/compiler.jar compiler/libbsl/bslbrowser.native tools/dissemination/spawn.sh compiler/libbsl/bslbrowser compiler/opa/gen_opa_manpage.native compiler/passlib/passdesign.native compiler/passlib/opatrack.sh compiler/compilerlib/opadep.sh ocamllib/libbase/testfilepos.native compiler/jslang/jsstat.native compiler/jslang/globalizer.native compiler/qmlcompilers/qmljs_exe.native tools/odep.native tools/odeplink.native compiler/opalang/opa2opa.native tools/ofile.native tools/manpages/genman.native compiler/opa/syntaxHelper.native compiler/opa/checkopacapi.native compiler/pplib/ppopa.native opa-node-packages.stamp qmljs.opa.create
> File "compiler/js_passes/_tags", line 7, characters 151-170:
> Warning: the tag "use_qmlfakecompiler" is not used in any flag or dependency declaration, so it will have no effect; it may be a typo. Otherwise you can use `mark_tag_used` in your myocamlbuild.ml to disable this warning.
> File "compiler/libbsl/_tags", line 6, characters 9-18:
> Warning: the tag "trx_cache" is not used in any flag or dependency declaration, so it will have no effect; it may be a typo. Otherwise you can use `mark_tag_used` in your myocamlbuild.ml to disable this warning.
> File "compiler/libbsl/_tags", line 10, characters 15-27:
> Warning: the tag "use_langlang" is not used in any flag or dependency declaration, so it will have no effect; it may be a typo. Otherwise you can use `mark_tag_used` in your myocamlbuild.ml to disable this warning.
> File "compiler/libbsl/_tags", line 30, characters 9-15:
> Warning: the tag "ignore" is not used in any flag or dependency declaration, so it will have no effect; it may be a typo. Otherwise you can use `mark_tag_used` in your myocamlbuild.ml to disable this warning.
> File "compiler/libbsl/_tags", line 33, characters 170-182:
> Warning: the tag "use_langlang" is not used in any flag or dependency declaration, so it will have no effect; it may be a typo. Otherwise you can use `mark_tag_used` in your myocamlbuild.ml to disable this warning.
> File "compiler/libtrx/_tags", line 1, characters 9-18:
> Warning: the tag "trx_cache" is not used in any flag or dependency declaration, so it will have no effect; it may be a typo. Otherwise you can use `mark_tag_used` in your myocamlbuild.ml to disable this warning.
> File "compiler/ocamllang/_tags", line 1, characters 20-29:
> Warning: the tag "trx_cache" is not used in any flag or dependency declaration, so it will have no effect; it may be a typo. Otherwise you can use `mark_tag_used` in your myocamlbuild.ml to disable this warning.
> File "compiler/opa/_tags", line 53, characters 60-79:
> Warning: the tag "use_qmlfakecompiler" is not used in any flag or dependency declaration, so it will have no effect; it may be a typo. Otherwise you can use `mark_tag_used` in your myocamlbuild.ml to disable this warning.
> File "compiler/opa/_tags", line 60, characters 130-149:
> Warning: the tag "use_qmlfakecompiler" is not used in any flag or dependency declaration, so it will have no effect; it may be a typo. Otherwise you can use `mark_tag_used` in your myocamlbuild.ml to disable this warning.
> File "compiler/opa/_tags", line 65, characters 262-281:
> Warning: the tag "use_qmlfakecompiler" is not used in any flag or dependency declaration, so it will have no effect; it may be a typo. Otherwise you can use `mark_tag_used` in your myocamlbuild.ml to disable this warning.
> File "compiler/opalang/_tags", line 17, characters 98-106:
> Warning: the tag "use_zlib" is not used in any flag or dependency declaration, so it will have no effect; it may be a typo. Otherwise you can use `mark_tag_used` in your myocamlbuild.ml to disable this warning.
> File "compiler/opalang/_tags", line 17, characters 67-76:
> Warning: the tag "use_mutex" is not used in any flag or dependency declaration, so it will have no effect; it may be a typo. Otherwise you can use `mark_tag_used` in your myocamlbuild.ml to disable this warning.
> File "compiler/opx2js/_tags", line 5, characters 227-246:
> Warning: the tag "use_qmlflatcompiler" is not used in any flag or dependency declaration, so it will have no effect; it may be a typo. Otherwise you can use `mark_tag_used` in your myocamlbuild.ml to disable this warning.
> File "compiler/opx2js/_tags", line 5, characters 206-225:
> Warning: the tag "use_qmlfakecompiler" is not used in any flag or dependency declaration, so it will have no effect; it may be a typo. Otherwise you can use `mark_tag_used` in your myocamlbuild.ml to disable this warning.
> File "compiler/qmlcps/_tags", line 4, characters 69-83:
> Warning: the tag "use_oparuntime" is not used in any flag or dependency declaration, so it will have no effect; it may be a typo. Otherwise you can use `mark_tag_used` in your myocamlbuild.ml to disable this warning.
> File "compiler/qmlcps/_tags", line 4, characters 53-67:
> Warning: the tag "use_appruntime" is not used in any flag or dependency declaration, so it will have no effect; it may be a typo. Otherwise you can use `mark_tag_used` in your myocamlbuild.ml to disable this warning.
> File "compiler/_tags", line 10, characters 213-232:
> Warning: the tag "use_qmlfakecompiler" is not used in any flag or dependency declaration, so it will have no effect; it may be a typo. Otherwise you can use `mark_tag_used` in your myocamlbuild.ml to disable this warning.
> File "lib/plugins/opabsl/_tags", line 20, characters 184-198:
> Warning: the tag "use_libsession" is not used in any flag or dependency declaration, so it will have no effect; it may be a typo. Otherwise you can use `mark_tag_used` in your myocamlbuild.ml to disable this warning.
> File "lib/plugins/opabsl/_tags", line 20, characters 166-182:
> Warning: the tag "use_qmlcpsserver" is not used in any flag or dependency declaration, so it will have no effect; it may be a typo. Otherwise you can use `mark_tag_used` in your myocamlbuild.ml to disable this warning.
> File "lib/plugins/opabsl/_tags", line 20, characters 152-164:
> Warning: the tag "use_database" is not used in any flag or dependency declaration, so it will have no effect; it may be a typo. Otherwise you can use `mark_tag_used` in your myocamlbuild.ml to disable this warning.
> File "lib/plugins/opabsl/_tags", line 20, characters 135-150:
> Warning: the tag "use_libsecurity" is not used in any flag or dependency declaration, so it will have no effect; it may be a typo. Otherwise you can use `mark_tag_used` in your myocamlbuild.ml to disable this warning.
> File "lib/plugins/opabsl/_tags", line 20, characters 123-133:
> Warning: the tag "use_libnet" is not used in any flag or dependency declaration, so it will have no effect; it may be a typo. Otherwise you can use `mark_tag_used` in your myocamlbuild.ml to disable this warning.
> File "lib/plugins/opabsl/_tags", line 20, characters 107-121:
> Warning: the tag "use_oparuntime" is not used in any flag or dependency declaration, so it will have no effect; it may be a typo. Otherwise you can use `mark_tag_used` in your myocamlbuild.ml to disable this warning.
> File "lib/plugins/opabsl/_tags", line 20, characters 91-105:
> Warning: the tag "use_appruntime" is not used in any flag or dependency declaration, so it will have no effect; it may be a typo. Otherwise you can use `mark_tag_used` in your myocamlbuild.ml to disable this warning.
> File "lib/plugins/opabsl/_tags", line 20, characters 75-89:
> Warning: the tag "use_libruntime" is not used in any flag or dependency declaration, so it will have no effect; it may be a typo. Otherwise you can use `mark_tag_used` in your myocamlbuild.ml to disable this warning.
> File "lib/plugins/opabsl/_tags", line 32, characters 181-195:
> Warning: the tag "use_oparuntime" is not used in any flag or dependency declaration, so it will have no effect; it may be a typo. Otherwise you can use `mark_tag_used` in your myocamlbuild.ml to disable this warning.
> File "lib/plugins/opabsl/_tags", line 32, characters 165-179:
> Warning: the tag "use_libsession" is not used in any flag or dependency declaration, so it will have no effect; it may be a typo. Otherwise you can use `mark_tag_used` in your myocamlbuild.ml to disable this warning.
> File "lib/plugins/opabsl/_tags", line 32, characters 149-163:
> Warning: the tag "use_libruntime" is not used in any flag or dependency declaration, so it will have no effect; it may be a typo. Otherwise you can use `mark_tag_used` in your myocamlbuild.ml to disable this warning.
> File "lib/plugins/opabsl/_tags", line 32, characters 131-147:
> Warning: the tag "use_qmlcpsserver" is not used in any flag or dependency declaration, so it will have no effect; it may be a typo. Otherwise you can use `mark_tag_used` in your myocamlbuild.ml to disable this warning.
> File "lib/plugins/opabsl/_tags", line 32, characters 117-129:
> Warning: the tag "use_database" is not used in any flag or dependency declaration, so it will have no effect; it may be a typo. Otherwise you can use `mark_tag_used` in your myocamlbuild.ml to disable this warning.
> File "lib/plugins/opabsl/_tags", line 32, characters 100-115:
> Warning: the tag "use_libsecurity" is not used in any flag or dependency declaration, so it will have no effect; it may be a typo. Otherwise you can use `mark_tag_used` in your myocamlbuild.ml to disable this warning.
> File "lib/plugins/opabsl/_tags", line 32, characters 84-98:
> Warning: the tag "use_appruntime" is not used in any flag or dependency declaration, so it will have no effect; it may be a typo. Otherwise you can use `mark_tag_used` in your myocamlbuild.ml to disable this warning.
> File "lib/plugins/opabsl/_tags", line 32, characters 72-82:
> Warning: the tag "use_libnet" is not used in any flag or dependency declaration, so it will have no effect; it may be a typo. Otherwise you can use `mark_tag_used` in your myocamlbuild.ml to disable this warning.
> File "lib/plugins/_tags", line 10, characters 20-26:
> Warning: the tag "static" is not used in any flag or dependency declaration, so it will have no effect; it may be a typo. Otherwise you can use `mark_tag_used` in your myocamlbuild.ml to disable this warning.
> File "tools/teerex/_tags", line 5, characters 9-18:
> Warning: the tag "trx_cache" is not used in any flag or dependency declaration, so it will have no effect; it may be a typo. Otherwise you can use `mark_tag_used` in your myocamlbuild.ml to disable this warning.
>  /Users/petros/.opam/4.04.2/bin/ocamlc.opt -c -g -warn-error A -w L -w Z -I compiler/buildinfos -I tools -I ocamllib -I lib -I compiler -I tools/build -o compiler/buildinfos/buildInfos.cmo compiler/buildinfos/buildInfos.ml
> File "compiler/buildinfos/buildInfos.ml", line 42, characters 12-27:
> Warning 52: Code should not depend on the actual values of
> this constructor's arguments. They are only for information
> and may change in future versions. (See manual section 8.5)
> File "compiler/buildinfos/buildInfos.ml", line 76, characters 12-27:
> Warning 52: Code should not depend on the actual values of
> this constructor's arguments. They are only for information
> and may change in future versions. (See manual section 8.5)

Error:
> File "compiler/buildinfos/buildInfos.ml", line 1:
> Error: compiler/buildinfos/buildInfos.cmi
> is not a compiled interface for this version of OCaml.
> It seems to be for a newer version of OCaml.
> Command exited with code 2.
> Compilation unsuccessful after building 10 targets (9 cached) in 00:00:02.
> make: *** [node] Error 10

My 'opam list'

> # Installed packages for 4.04.2:
> base-bigarray     base  Bigarray library distributed with the OCaml compiler
> base-bytes        base  Bytes library distributed with the OCaml compiler
> base-threads      base  Threads library distributed with the OCaml compiler
> base-unix         base  Unix library distributed with the OCaml compiler
> camlp4          4.04+1  Camlp4 is a system for writing extensible parsers for programming languages
> camlzip           1.07  Provides easy access to compressed files in ZIP, GZIP and JAR format
> conf-m4              1  Virtual package relying on m4
> ocamlbuild      0.12.0  OCamlbuild is a build system with builtin rules to easily build most OCaml projects.
> ocamlfind      1.7.3-1  A library manager for OCaml
> ocamlgraph       1.8.8  A generic graph library for OCaml
> ulex               1.2  lexer generator for Unicode and OCaml

Hope you can get something out of this

**Comment by hbbio** [comment]
Maybe you need to `make clean` and run `configure` again before build.

**Comment by igneel64** [comment]
Sorry for the late response! Yes, it now works perfectly the key was to run:
`make clean`
