### ISSUE TITLE
Opa just removed my PATH in windows

### ISSUE THREAD

**Issue by rikkertkoppes** [MLstate/opalang#87]
install got interrupted, result: my PATH is borked:

suggestion: change line 6 of opa.bat:

    set PATH=%OLDPATH%;%OPABASEDIR%\bin;%OPABASEDIRMINGW%\bin

**Comment by hbbio** [comment]
Windows was a community contribution. Right now, we recommend to use Docker/Vagrant to run Opa from a linux virtual machine in Windows.
